[project]
name = "simple-mesh-tracing"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "opentelemetry-distro>=0.53b1",
    "opentelemetry-exporter-otlp>=1.32.1",
    "opentelemetry-instrumentation-asyncio==0.53b1",
    "opentelemetry-instrumentation-click==0.53b1",
    "opentelemetry-instrumentation-dbapi==0.53b1",
    "opentelemetry-instrumentation-fastapi==0.53b1",
    "opentelemetry-instrumentation-grpc==0.53b1",
    "opentelemetry-instrumentation-logging==0.53b1",
    "opentelemetry-instrumentation-requests==0.53b1",
    "opentelemetry-instrumentation-sqlite3==0.53b1",
    "opentelemetry-instrumentation-starlette==0.53b1",
    "opentelemetry-instrumentation-threading==0.53b1",
    "opentelemetry-instrumentation-tortoiseorm==0.53b1",
    "opentelemetry-instrumentation-urllib==0.53b1",
    "opentelemetry-instrumentation-urllib3==0.53b1",
    "opentelemetry-instrumentation-wsgi==0.53b1",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "pydantic-settings>=2.9.1",
    "requests>=2.32.3",
    "uvicorn>=0.34.2",
]
